# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            CALEB BRENDEN
tagline:          HEY!
description:      'albuquerque, nm'
url:              https://fongandrew.github.io/hydeout
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Caleb Brenden'
  url:            https://twitter.com/calebbrenden

paginate:         5
paginate_path:    '/blog/page:num'
                    #'/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.6.0
sidebar_home_link:  true
sidebar_blog_link:  #'/blog.html'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
                              
github:
  repo:             https://github.com/calebbreadsticks

encoding: UTF-8


