# Dependencies
markdown:         kramdown
highlighter:      rouge
parse_block_html: true

# Setup
title:            CALEB BRENDEN
tagline:          'student, web designer, photographer. albuquerque, new mexico.'
description:      'student, web designer, photographer. albuquerque, new mexico.'
url:              https://calebbrenden.github.io/
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:           Caleb Brenden
twitter:          
  username: calebbrenden
social:
  name: Caleb Brenden
  links:
    - https://instagram.com/calebbreadsticks
    - https://twitter.com/calebbrenden

paginate:         5
paginate_path:    '/thoughts/page:num'
                    #'/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:            3.6.0
sidebar_home_link:  true
sidebar_blog_link:  '/thoughts'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
                              
github:
  repo:             https://github.com/calebbreadsticks

encoding: UTF-8


